import re
from typing import Any, Dict, List, Set

import structlog

logger = structlog.get_logger(__name__)


def resolve_citations(
    response_text: str,
    candidates: List[Dict[str, Any]],
    verified_math_vars: Optional[Dict[str, Any]] = None,
) -> List[Dict[str, Any]]:
    """Parse inline citation tags (e.g. [Chunk X]) from LLM response text and resolve to Coordinate CitationObjects.

    Args:
        response_text: Raw synthesized text generated by the LLM.
        candidates: List of retrieved candidate chunk metadata profiles.
        verified_math_vars: Dict of verified variable key-value mappings from the sandbox auditor.

    Returns:
        List of serialized CitationObject dictionaries.
    """
    logger.info("Resolving coordinate citations from response text")
    citations: List[Dict[str, Any]] = []

    # Regex mapping surrounding sentences matching [Chunk X]
    chunk_citations = re.findall(r"([^.!?\n]*?\[Chunk (\d+)\])", response_text)
    resolved_chunk_indices: Set[int] = set()

    # Math numbers to verify chunk alignment
    math_numbers: Set[float] = set()
    if verified_math_vars:
        for val in verified_math_vars.values():
            if isinstance(val, (int, float)):
                math_numbers.add(float(val))

    for cit_sentence, chunk_idx_str in chunk_citations:
        chunk_idx = int(chunk_idx_str) - 1
        if 0 <= chunk_idx < len(candidates):
            candidate = candidates[chunk_idx]
            clean_text = re.sub(r"\[Chunk \d+\]", "", cit_sentence).strip()

            # Ensure coordinates bounding box format fits schema
            bbox_raw = candidate.get("bounding_box") or [0.0, 0.0, 0.0, 0.0]
            if isinstance(bbox_raw, dict):
                bbox = {
                    "x1": float(bbox_raw.get("x1", 0.0)),
                    "y1": float(bbox_raw.get("y1", 0.0)),
                    "x2": float(bbox_raw.get("x2", 0.0)),
                    "y2": float(bbox_raw.get("y2", 0.0)),
                }
            elif isinstance(bbox_raw, list) and len(bbox_raw) >= 4:
                bbox = {
                    "x1": float(bbox_raw[0]),
                    "y1": float(bbox_raw[1]),
                    "x2": float(bbox_raw[2]),
                    "y2": float(bbox_raw[3]),
                }
            else:
                bbox = {"x1": 0.0, "y1": 0.0, "x2": 0.0, "y2": 0.0}

            # Map verification status: check if chunk text has numbers whitelisted in verified math
            is_verified = False
            chunk_text = candidate.get("chunk_text") or ""
            for num in math_numbers:
                if str(int(num)) in chunk_text or f"{num:.2f}" in chunk_text:
                    is_verified = True
                    break

            # Calculate confidence indicators
            similarity_score = float(candidate.get("score", 0.85))
            reranker_score = candidate.get("rerank_score")
            if reranker_score is not None:
                reranker_score = float(reranker_score)

            citation_obj = {
                "chunk_id": candidate["id"],
                "document_id": candidate["document_id"],
                "page": int(candidate["page_number"]),
                "bbox": bbox,
                "section": candidate.get("parent_header"),
                "ticker": candidate.get("ticker", "UNKNOWN"),
                "period": candidate.get("period", "UNKNOWN"),
                "confidence": {
                    "similarity_score": similarity_score,
                    "reranker_score": reranker_score,
                    "verification_status": "verified" if is_verified else "unverified",
                },
            }
            citations.append(citation_obj)
            resolved_chunk_indices.add(chunk_idx)

    # Fallback scan for inline tags not mapped in sentence splits
    for match in re.finditer(r"\[Chunk (\d+)\]", response_text):
        chunk_idx = int(match.group(1)) - 1
        if chunk_idx not in resolved_chunk_indices and 0 <= chunk_idx < len(candidates):
            candidate = candidates[chunk_idx]
            bbox_raw = candidate.get("bounding_box") or [0.0, 0.0, 0.0, 0.0]
            if isinstance(bbox_raw, list) and len(bbox_raw) >= 4:
                bbox = {
                    "x1": float(bbox_raw[0]),
                    "y1": float(bbox_raw[1]),
                    "x2": float(bbox_raw[2]),
                    "y2": float(bbox_raw[3]),
                }
            else:
                bbox = {"x1": 0.0, "y1": 0.0, "x2": 0.0, "y2": 0.0}

            citation_obj = {
                "chunk_id": candidate["id"],
                "document_id": candidate["document_id"],
                "page": int(candidate["page_number"]),
                "bbox": bbox,
                "section": candidate.get("parent_header"),
                "ticker": candidate.get("ticker", "UNKNOWN"),
                "period": candidate.get("period", "UNKNOWN"),
                "confidence": {
                    "similarity_score": float(candidate.get("score", 0.85)),
                    "reranker_score": None,
                    "verification_status": "unverified",
                },
            }
            citations.append(citation_obj)
            resolved_chunk_indices.add(chunk_idx)

    logger.info("Citations resolution completed", count=len(citations))
    return citations
